name: Deploy mdBook site

on:
  # Triggers the workflow on push events to the main branch
  push:
    branches:
      - main # Adjust if your default branch is 'master'

# Allow this job to push to the gh-pages branch
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'

      - name: Build mdBook
        # Builds the book into the 'book' directory
        run: mdbook build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Directory to deploy
          publish_dir: ./book
          # Creates a clean branch history
          force_orphan: true